feat: 회원가입, 로그인, 로그아웃 기능 추가
delicious-algorithme/matal-server pull request #41
Opened 2024-10-02 11:22 UTC by mrri-18

PR 타입
기능 추가

변경 사항
Member 엔티티 컬럼명 수정
jwt 도메인 생성
토큰을 생성하는 jwtutil class 구현
토큰이 유효한지 검증하는 jwtfilter class 구현
각 기능에 대한 controller, service, repository 구현
테스트 결과
 컨트롤러 & 서비스 로직 테스트 진행

2024-10-02 18:03 UTC, gogo1414 requested changes
안녕하세요, 민경님😊
회원 기능 만드시느라 고생 많으셨어요! 여기 저기 고민하신 흔적도 보이지만, 사실 어떠한 의도로 이렇게 코드를 작성하셨는지 궁금한 부분이 더 많았어요!
차근차근 얘기해보도록 하겠습니다!

1. `dto` 객체에 `final`을 붙이지 않으신 의도가 궁금해요! dto 는 data transfer object의 약자로 정말 데이터를 전달하는 단순 전달자의 역할만 할 뿐인데 필드 값이 변경될 수 있게 하신 이유가 존재할까요?
2. `Member`, `BlackList`의 분리 이유가 궁금해요! Member 객체 안에서 `refreshToken`을 두게 되면 각 회원의 `accessToken` 발급을 더 쉽게 할 수 있진 않을까요?
3. Member 필드명에서 저희 서비스에는 필요해보이지 않는 필드명이 있진 않나요?? 사실 로그인 기능이 필요한 이유가 현재 북마크 기능의 활성화 하나 때문인데, 생일과 이름을 받는다는 것은 현재 서비스 내에서 불필요해 보여서 여쭤봅니다!
4. `spring security`의 필터 구조가 매우 복잡해서 정말 잘 활용하기 까지는 매우 긴 시간이 필요하다고 하네요..([spring security 심화](https://velog.io/@on5949/SpringSecurity-%EC%8A%A4%ED%94%84%EB%A7%81-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0-%ED%95%84%ED%84%B0-%EC%B2%B4%EC%9D%B8-%EC%8B%AC%ED%99%94)) 그래서 spring security 가 아닌 저희가 필요한 부분만을 구축하는 방식은 어떤지 고민해보는 시간이 있으면 좋을거 같아요!

전반적으로 코드 컨벤션에 맞게 코드 리팩터링이 많이 필요해보여요! 그리고 정말 사용하고자 했던 부분이 어떠한 근거를 가지고 사용하고 계신지 설명을 해주시면 좋을거 같아요!

내일이 여행 출국일이라 하루 안에 제가 제시한 문제들과 질문을 모두 해결할 수 있는 충분한 시간이라고 생각이 들진 않아요... 다 해결하시기 보다는 닿는데 까지 해결해주시면 될 것 같습니다!

고생하셨어요!😊

2024-10-03 04:21 UTC, mrri-18 commented on src/main/java/matal/member/entity/Member.java
name은 기존에 있었고, 추후에 로그 기능을 도입한다면 나이대별로 예를 들어, 10대/20대/30대 등 회원들이 많이 선택한 식당만 추려서 메인에서 보여주는 기능은 어떨까 싶어서 추가했습니다!

2024-10-03 04:29 UTC, mrri-18 commented on src/main/java/matal/jwt/entity/BlackList.java
그 부분도 생각을 했는데 jwt 관련 데이터는 저희 프로젝트 구조 상 jwt에 해당된다고 생각해서 엔티티를 따로 만들었습니다.

2024-10-03 04:49 UTC, mrri-18 commented on src/main/java/matal/member/dto/LoginResponse.java
수정하겠습니다!

2024-10-03 05:02 UTC, mrri-18 commented on src/main/java/matal/member/repository/MemberRepository.java
> +    boolean existsByEmail(String email);// 중복 가입 확인
반환되는 내용이 둘 중 하나여서 그렇게 처리했는데 수정할까요?

2024-10-03 05:12 UTC, mrri-18 commented on src/main/java/matal/member/entity/Member.java
> +    private String pwd;
추후 반영하겠습니다!

2024-10-03 07:13 UTC, gogo1414 commented on src/main/java/matal/member/repository/MemberRepository.java
> +    boolean existsByEmail(String email);// 중복 가입 확인
반환이 NULL로 되지 않는다는게 검증되면 수정할 필요는 없을거 같아요!

2024-10-03 07:14 UTC, gogo1414 commented on src/main/java/matal/jwt/entity/BlackList.java
말씀해주신 부분이 조금 이해가 안가는데 프로젝트 구조 상 jwt에 해당된다는게 무슨 의미인가요??

각 회원별로 리프레시 토큰이 따로 존재하는게 아니라는 의미일까요??

2024-10-03 07:16 UTC, gogo1414 commented on src/main/java/matal/member/entity/Member.java
확장 가능성을 고려하셔서 개발을 진행한 점은 매우 좋네요! 다만, 저희의 목표가 10월까지 회원 기능 도입을 목표로 하니 필요한 부분만 빠르게 개발하고 나중에 고객이 생길 때 그런 기능을 추가를 고민하는게 더 좋지 않을까요?

2024-10-03 07:30 UTC, mrri-18 commented on src/main/java/matal/jwt/entity/BlackList.java
토큰 저장하는 방법을 저도 고민해봤는데 계층적 구조로 생각했을 때 토큰을 저장하는 용도라고 생각해서 아예 엔티티를 새로 만들었거든요 멤버에 추가하는게 좋을까요?

2024-10-03 07:33 UTC, mrri-18 commented on src/main/java/matal/member/service/MemberService.java
> +}
다른 방법이 있나요..? global안에서 예외처리를 하자는 말씀이실까요?

2024-11-23 16:30 UTC, closed without merging