feat: 검색 기능 개발
delicious-algorithme/matal-server pull request #8
Opened 2024-08-11 11:55 UTC by yeoncheong08

## 개요

- 가게 이름, 카테고리, 지하철 역을 검색한 결과 가게 리스트를 조회할 수 있다.

### PR 타입

- 기능 추가
- 구조 및 설정 재구성

### 반영 브랜치

- feature/store -> feature/store

## 변경 사항

- swagger 의존성 추가
- swagger config 설정
- 패키지 구조 재구성 (config, member, store로 구분)
- Store 엔티티 컬럼 실제 데이터컬럼에 맞게 수정
- name, category, nearby_station 검색 기능 구현

### 테스트 결과

- [O] StoreService 메서드 테스트 완료

2024-08-12 03:59 UTC, gogo1414 requested changes
안녕하세요, 려하님!

전체적으로 너무 잘 작성해주신거 같아요!
전체적으로 읽으면서 의문점이 든 부분과 컨벤션에 어긋난 부분만 코드 리뷰를 작성했어요! 참고하셔서 수정해주시면 좋을거 같아요!

마지막으로 dto를 작성해주셨는데 record 객체에 대해 어떻게 생각하시는지 궁금해요.
간단한 설명과 장/단점을 정리해서 노션에 정리해봤어요!(자세한 내용은 노션 안 URL을 참고해주세요!)
[Record객체란?](https://wnstn6945.notion.site/Record-592eaa79b53842c690b82d0b61ff1019?pvs=25)

고생하셨어요!

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/repository/StoreRepository.java
> +    List<Store> findByNameContaining(String searchKeyword);
첫 줄 공백 부탁드려요!

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/controller/StoreController.java
> +    }
해당 부분이 가게이름, 카테고리, 근처 지하철 역에 해당하는 모든 가게들을 조회하는 것처럼 보이는데 어떤 부분에서 필요한 지 잘 이해를 못했는데 혹시 설명해주실 수 있나요?

각각 조회할 수 있게 만들면 더 좋지 않을까요?😊

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/controller/StoreController.java
> +    ) {
해당 부분은 한 줄로 작성하는게 더 보기 좋을거 같아요!

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/repository/StoreRepository.java
서비스 계층에서 Optional을 사용하셨던데, 데이터베이스에서 데이터를 조회할 때 Optional<>을 붙여보는 건 어떨까요?

[Optional이란?](https://mangkyu.tistory.com/70)

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/service/StoreService.java
stream 사용하셔서 깔끔하게 정리했네요!!
멋지십니다👍

2024-08-12 03:59 UTC, gogo1414 commented on src/main/java/matal/store/controller/StoreController.java
> +    private final StoreRepository storeRepository;
`StoreService`계층으로 분리하여 진행중이니 `StoreRepository`은 없어도 되지 않을까요??

2024-08-12 12:39 UTC, yeoncheong08 commented on src/main/java/matal/store/controller/StoreController.java
> +    }
마침 저도 컨트롤러 작성하면서 각각 조회할지 한번에 조회할지 고민하던 부분이었어요!  유연성을 위해서 분리시키는게 좋을 것 같네요. 감사합니다!

2024-08-12 12:41 UTC, yeoncheong08 commented on src/main/java/matal/store/controller/StoreController.java
> +    ) {
앗,,,가게 상세정보 조회는 제가 아직 구현을 못 해서....제외하고 커밋한다는걸 깜빡한 것 같습니다. 코멘트 달아주셔서 감사해요!

2024-08-12 12:44 UTC, yeoncheong08 commented on src/main/java/matal/store/controller/StoreController.java
> +    private final StoreRepository storeRepository;
아래에 가게 상세 정보 조회 매핑할 때 쓰려고 했던 흔적인 것 같네요... ㅋㅋㅋㅋㅋ 아직 구현을 안 했지만 구현한 뒤에는 삭제될 것 같습니다! 피드백 감사합니다

2024-08-17 01:16 UTC, gogo1414 reviewed
고생하셨어요!
예외처리 부분은 나중에 적용해보도록 해요!

2024-08-17 05:43 UTC, gogo1414 approved these changes
고생하셨어요!

2024-08-17 05:43 UTC, merged